databases:
  - name: jobportal_db
    user: jobportal_user
    plan: free
    region: singapore

services:
  - type: web
    name: jobportal-backend
    env: python
    region: singapore
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobportal_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com localhost 127.0.0.1"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: PYTHON_VERSION
        value: "3.11.0"

  - type: web
    name: jobportal-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: jobportal-backend
          envVarKey: RENDER_EXTERNAL_URL
