databases:
  - name: jobportal-db-production
    user: jobportal
    region: singapore

services:
  - type: web
    name: jobportal-backend-production
    env: python
    region: singapore
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobportal-db-production
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com localhost 127.0.0.1"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"

  - type: web
    name: jobportal-frontend-production
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: jobportal-backend-production
          envVarKey: RENDER_EXTERNAL_URL
